### ISSUE TITLE
Falta documentacion

### ISSUE THREAD

**Issue by SARQUIS-BOUTROS** [salvadorjesus/Java-Motor-Red-Neuronal#1]
Saludos, estuve intentando entender que hace tu red neuronal (como implementa la solucion) y habre estado cerca de 90 horas (estoy divagando) intentando entender los parametros del objeto RedNeuronal, podrias explicarme como funciona el test? 

Gracias

**Comment by yogonza524** [comment]
Acompaño el pedido del amigo Sarquis, voy a sentarme a escribir en mi maquina de escribir "invisible" la respuesta. Gracias de antemano. Saludos

**Comment by salvadorjesus** [comment]
Acabo de añadir documentación al constructor de la clase RedNeuronal y he actualizado todo el Javadoc.  Está todo en master.
